# Generated by Django 2.2.11 on 2020-06-19 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_usersession'),
    ]

    operations = [
        migrations.RenameField(
            model_name='objectviewed',
            old_name='ip_addess',
            new_name='ip_address',
        ),
        migrations.RenameField(
            model_name='usersession',
            old_name='ip_addess',
            new_name='ip_address',
        ),
    ]
