# Generated by Django 2.2.11 on 2020-06-27 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_marketingpreference_mailchimp_subscribed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketingpreference',
            name='timestamp',
        ),
    ]
